"""Store user uploads under the SlotFlow workspace."""

from __future__ import annotations

import json
import re
from pathlib import Path

from app.chat.ids import new_file_id
from app.harness.sandbox import (
    SlotFlowSandboxConfig,
    WorkspaceFileTooLargeError,
    build_slotflow_workspace,
)
from app.uploads.models import UploadedFileRecord


class UploadNotFoundError(FileNotFoundError):
    """Raised when an uploaded file ID has no metadata."""


class UploadFileTooLargeError(WorkspaceFileTooLargeError):
    """Raised when an upload exceeds configured size limits."""


class SlotFlowUploadStore:
    """Persist uploaded files inside `workspace/uploads`."""

    def __init__(self, config: SlotFlowSandboxConfig | None = None) -> None:
        self.workspace = build_slotflow_workspace(config)

    @property
    def max_upload_bytes(self) -> int:
        """Reuse the workspace write limit for explicit user uploads."""

        return self.workspace.config.max_write_bytes

    def save_upload(
        self,
        *,
        filename: str,
        content_type: str | None,
        data: bytes,
    ) -> UploadedFileRecord:
        """Write uploaded bytes and metadata under a new file ID."""

        if len(data) > self.max_upload_bytes:
            raise UploadFileTooLargeError(
                "upload exceeds max_upload_bytes: "
                f"{len(data)} > {self.max_upload_bytes}",
            )

        file_id = new_file_id()
        safe_filename = sanitize_upload_filename(filename)
        workspace_path = f"uploads/{file_id}/{safe_filename}"
        target = self.workspace.resolve_path(workspace_path)
        metadata_target = self._metadata_path(file_id)

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)

        record = UploadedFileRecord(
            id=file_id,
            filename=safe_filename,
            content_type=content_type,
            size_bytes=len(data),
            workspace_path=workspace_path,
        )
        metadata_target.write_text(
            json.dumps(record.model_dump(mode="json"), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        return record

    def get_upload(self, file_id: str) -> UploadedFileRecord:
        """Read uploaded file metadata by ID."""

        metadata_target = self._metadata_path(file_id)
        if not metadata_target.is_file():
            raise UploadNotFoundError(f"upload not found: {file_id}")
        return UploadedFileRecord.model_validate_json(
            metadata_target.read_text(encoding="utf-8")
        )

    def get_upload_path(self, file_id: str) -> Path:
        """Resolve the stored file path for an upload ID."""

        record = self.get_upload(file_id)
        return self.workspace.resolve_path(record.workspace_path)

    def _metadata_path(self, file_id: str) -> Path:
        validate_upload_id(file_id)
        target = self.workspace.resolve_path(f"uploads/{file_id}/metadata.json")
        target.parent.mkdir(parents=True, exist_ok=True)
        return target


def sanitize_upload_filename(filename: str | None) -> str:
    """Make user-supplied filenames safe for workspace storage."""

    raw = (filename or "").replace("\\", "/").split("/")[-1].strip()
    if not raw:
        raw = "upload.bin"

    sanitized = re.sub(r"[^A-Za-z0-9._-]+", "_", raw).strip("._")
    if not sanitized:
        sanitized = "upload.bin"
    if len(sanitized) <= 128:
        return sanitized

    stem, dot, suffix = sanitized.rpartition(".")
    if dot and suffix:
        return f"{stem[: 127 - len(suffix)]}.{suffix}"[:128]
    return sanitized[:128]


def validate_upload_id(file_id: str) -> None:
    """Accept only IDs generated by `new_file_id()`."""

    if not re.fullmatch(r"file_[0-9a-f]{12}", file_id):
        raise UploadNotFoundError(f"upload not found: {file_id}")
